### ISSUE TITLE
Link to "Pi-hole: upstream DNS server" missing

### ISSUE THREAD

**Issue by beerisgood** [commonshost/dohnut#13]
In readme the link to [Pi-hole: upstream DNS server](https://raw.githubusercontent.com/commonshost/dohnut/master/docs/pihole) ends in 404 error

**Comment by sebdeckers** [comment]
Ohhh good find. It's actually a bug (or missing feature) in the static site generator for the documentation site. I'll add support for relative link path rewriting to the [build.js](https://gitlab.com/commonshost/documentation/blob/master/build.js) script.

**Comment by sebdeckers** [comment]
👌🏻 Closed in https://gitlab.com/commonshost/documentation/commit/d58586980fc379aef07af42f6e262f46f0b96ff8
