### ISSUE TITLE
Debian on vps error: socket name does not exist; No local DNS listeners specified

### ISSUE THREAD

**Issue by beatstick** [commonshost/dohnut#24]
Hi, 
I am trying to run dohnut on debian 10. I set everything up according to https://github.com/commonshost/dohnut/tree/master/docs/systemd

The service crashes when I start it using: dig @127.0.0.1 -p 53000 example.com
I get an error message: url cannot be reached.

$ journalctl -f -n 100 -u dohnut
May 15 23:38:53 systemd[1]: dohnut.service: Main process exited, code=exited, status=1/FAILURE
May 15 23:38:53 systemd[1]: dohnut.service: Failed with result 'exit-code'.
May 15 23:38:53  systemd[1]: Failed to start Dohnut DNS over HTTPS proxy.
May 15 23:38:53  systemd[1]: dohnut.service: Service RestartSec=100ms expired, scheduling restart.
May 15 23:38:53 systemd[1]: dohnut.service: Scheduled restart job, restart counter is at 4.
 systemd[1]: Stopped Dohnut DNS over HTTPS proxy.
 systemd[1]: Starting Dohnut DNS over HTTPS proxy...
 dohnut[3124]: The socket name specified does not exist
dohnut[3124]: Trace: Error: No local DNS listeners specified.
dohnut[3124]:     at parseOptions (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:99:11)
dohnut[3124]:     at main (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:201:25)
 dohnut[3124]:     at Object.<anonymous> (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:240:1)
dohnut[3124]:     at Module._compile (internal/modules/cjs/loader.js:1176:30)
dohnut[3124]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
 dohnut[3124]:     at Module.load (internal/modules/cjs/loader.js:1040:32)
 dohnut[3124]:     at Function.Module._load (internal/modules/cjs/loader.js:929:14)
dohnut[3124]:     at Module.require (internal/modules/cjs/loader.js:1080:19)
dohnut[3124]:     at require (internal/modules/cjs/helpers.js:72:18)
 dohnut[3124]:     at Object.<anonymous> (/home/dohnut/n/lib/node_modules/dohnut/source/bin.js:5:1)
 dohnut[3124]:     at /home/dohnut/n/lib/node_modules/dohnut/source/cli.js:243:13
 systemd[1]: dohnut.service: Main process exited, code=exited, status=1/FAILURE

I am not sure what went wrong, it's probably to do with slight differences between ubuntu and debian, but I've no clue what command has to be changed.

**Comment by qoelet** [comment]
@beatstick can you share what's the output for `systemctl status dohnut.socket`?

**Comment by beatstick** [comment]
@qoelet 

● dohnut.socket
   Loaded: loaded (/etc/systemd/system/dohnut.socket; enabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Sat 2020-05-16 20:26:33 CEST; 1 day 21h ago
   Listen: 127.0.0.1:53000 (Datagram)

May 16 19:42:55 v2202003116164111254 systemd[1]: Listening on dohnut.socket.
May 16 20:26:33 v2202003116164111254 systemd[1]: dohnut.socket: Failed with result 'service-start-limit-hit'.

---------------------------

 sudo systemctl restart dohnut.socket

$ sudo systemctl status dohnut.socket
● dohnut.socket
   Loaded: loaded (/etc/systemd/system/dohnut.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Mon 2020-05-18 17:47:26 CEST; 3s ago
   Listen: 127.0.0.1:53000 (Datagram)
    Tasks: 0 (limit: 2359)
   Memory: 20.0K
   CGroup: /system.slice/dohnut.socket


The socket goes down once I start a dns lookup:

 sudo dig @127.0.0.1 -p 53000 web.de

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @127.0.0.1 -p 53000 web.de
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

sudo systemctl status dohnut.socket
● dohnut.socket
   Loaded: loaded (/etc/systemd/system/dohnut.socket; enabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Mon 2020-05-18 17:48:51 CEST; 49s ago
   Listen: 127.0.0.1:53000 (Datagram)

May 18 17:47:26  systemd[1]: Listening on dohnut.socket.
May 18 17:48:51  systemd[1]: dohnut.socket: Failed with result 'service-start-limit-hit'.

Not very helpful, I guess...

**Comment by qoelet** [comment]
@beatstick looks like dohnut isn't able to start (due to some misconfiguration); the error above just seems to look like systemd restarting too many times/too quickly. Are you able to look through the logs in detail for any hints of what might have gone wrong? i.e. `journalctl -xe`

**Comment by beatstick** [comment]
May 18 17:48:49  dohnut[11299]: The socket name specified does not exist
May 18 17:48:49 dohnut[11299]: Trace: Error: No local DNS listeners specified.
May 18 17:48:49  dohnut[11299]:     at parseOptions (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:99:11)
May 18 17:48:49  dohnut[11299]:     at main (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:201:25)
May 18 17:48:49  dohnut[11299]:     at Object.<anonymous> (/home/dohnut/n/lib/node_modules/dohnut/source/cli.js:240:1)
May 18 17:48:49  dohnut[11299]:     at Module._compile (internal/modules/cjs/loader.js:1176:30)
May 18 17:48:49  dohnut[11299]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
May 18 17:48:49  dohnut[11299]:     at Module.load (internal/modules/cjs/loader.js:1040:32)
May 18 17:48:49  dohnut[11299]:     at Function.Module._load (internal/modules/cjs/loader.js:929:14)
May 18 17:48:49  dohnut[11299]:     at Module.require (internal/modules/cjs/loader.js:1080:19)
May 18 17:48:49  dohnut[11299]:     at require (internal/modules/cjs/helpers.js:72:18)
May 18 17:48:49  dohnut[11299]:     at Object.<anonymous> (/home/dohnut/n/lib/node_modules/dohnut/source/bin.js:5:1)
May 18 17:48:49  dohnut[11299]:     at /home/dohnut/n/lib/node_modules/dohnut/source/cli.js:243:13


This is repeated several times before the services stops restarting. --Socket name does not exist and no local dns listeners specified is the gist of it I think.

**Comment by sebdeckers** [comment]
I was able to reproduce this on a Raspberry Pi 3 B+ under Ubuntu 20.04 by simply following the tutorial.

Findings:
The error message `The socket name specified does not exist` is because Dohnut was looking for a file descriptor named `dohnut` instead of `dohnut.socket` [as provided by systemd by default](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#FileDescriptorName=). It looks this bug was introduced after writing the systemd tutorial.

Fix:
The following line should be added in `/etc/systemd/system/dohnut.socket`:

```diff
[Socket]
ListenDatagram=127.0.0.1:53000
ReusePort=true
+FileDescriptorName=dohnut

[Install]
WantedBy=sockets.target
```
(the `+` prefix is only for highlighting here, don't add it to the file 😉)

Then apply the changed configuration and try again:

```shell
$ sudo systemctl daemon-reload
$ sudo systemctl stop dohnut.service
$ sudo systemctl restart dohnut.socket
$ dig @127.0.0.1 -p 53000 example.com
```

Docs updated:
https://help.commons.host/dohnut/systemd/

Patch:
https://github.com/commonshost/dohnut/commit/46e51b995775c019468bba46c3ab5798e096fb4f
(docs changed only, no update of Dohnut is required)

**Comment by beatstick** [comment]
@sebdeckers:
Thanks. That does indeed do the trick!

If someone needs instructions how to get access to the server from another network:
I set the listening port to the default port: 53 (to not run into further complications) and opened the port on the firewall:

sudo ufw allow dns
sudo ufw reload

 sudo nano /etc/systemd/system/dohnut.socket


[Socket]
#ListenDatagram=127.0.0.1:53000
ListenDatagram=0.0.0.0:53

#I think 0.0.0.0 should work, if not use your servers external ip.
